RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/config
PATH=$PATH:/usr/local/go/bin
PATH=$HOME/.cargo/bin:$PATH
PATH=$HOME/go/bin:$PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/.local/bin:$PATH
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
SSH_ASKPASS=/usr/libexec/openssh/lxqt-openssh-askpass
QT_QPA_PLATFORMTHEME=qt5ct
TERMINAL=kitty
EDITOR=nvim
HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
